amcl:
  ros__parameters:
    use_sim_time: false

    # 프레임
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"

    # 라이다
    scan_topic: "scan"

    # AMCL 튜닝(초기값은 무난)
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    update_min_d: 0.25
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 0.5
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    tf_broadcast: true

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""   # launch에서 map 경로를 주입할 예정

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ["map_server", "amcl"]
